In [1]:
import duckdb as db
import pandas as pd

In [2]:
visimages = db.connect("./visimages.db")

In [3]:
visimages.sql("SHOW TABLES").show()

┌─────────────────┐
│      name       │
│     varchar     │
├─────────────────┤
│ author          │
│ contribution    │
│ figure          │
│ figure_property │
│ institution     │
│ paper           │
│ residence       │
└─────────────────┘

In [4]:
visimages.sql("SELECT * FROM paper").show()

┌────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────┬──────────────────┬───────────────────────────────────────────────────────────────────────────────────────┬──────────┬───────────┐
│     id     │                                                         title                                                          │                    doi                     │ publication_date │                                        oa_url                                         │ pdf_path │  inst_id  │
│   int64    │                                                        varchar                                                         │                  varchar                   │       date       │                                        varchar                                        │ varchar  │   int64   │
├────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────┼──────────────────┼───────────────────────────────────────────────────────────────────────────────────────┼──────────┼───────────┤
│ 3085563693 │ Surface representations of two- and three-dimensional fluid flow topology                                              │ https://doi.org/10.1109/visual.1990.146359 │ 2002-12-04       │ None                                                                                  │ NULL     │ 138006243 │
│ 3041520455 │ FAST: a multi-processed environment for visualization of computational fluid dynamics                                  │ https://doi.org/10.1109/visual.1990.146360 │ 2002-12-04       │ https://jaxa.repo.nii.ac.jp/record/43435/files/nalsp0014002.pdf                       │ NULL     │ 138006243 │
│ 4237685258 │ The VIS-5D system for easy interactive visualization                                                                   │ https://doi.org/10.1109/visual.1990.146361 │ 2002-12-04       │ None                                                                                  │ NULL     │ 138006243 │
│ 4241306103 │ A procedural interface for volume rendering                                                                            │ https://doi.org/10.1109/visual.1990.146362 │ 2002-12-04       │ None                                                                                  │ NULL     │ 138006243 │
│ 4242274056 │ Techniques for the interactive visualization of volumetric data                                                        │ https://doi.org/10.1109/visual.1990.146363 │ 2002-12-04       │ https://escholarship.org/content/qt4367m3t4/qt4367m3t4.pdf?t=ptt2h6                   │ NULL     │ 138006243 │
│ 4235544651 │ Displaying voxel-based objects according to their qualitative shape synthesis                                          │ https://doi.org/10.1109/visual.1990.146364 │ 2002-12-04       │ None                                                                                  │ NULL     │ 138006243 │
│ 4243289651 │ Interpreting a 3D object from a rough 2D line drawing                                                                  │ https://doi.org/10.1109/visual.1990.146365 │ 2002-12-04       │ None                                                                                  │ NULL     │ 138006243 │
│ 4232108933 │ Animation techniques for chain-coded objects                                                                           │ https://doi.org/10.1109/visual.1990.146366 │ 2002-12-04       │ None                                                                                  │ NULL     │ 138006243 │
│ 4239445310 │ Extracting geometric models through constraint minimization                                                            │ https://doi.org/10.1109/visual.1990.146367 │ 2002-12-04       │ None                                                                                  │ NULL     │ 138006243 │
│ 4252612379 │ Wide-band relativistic Doppler effect visualization                                                                    │ https://doi.org/10.1109/visual.1990.146368 │ 2002-12-04       │ http://www.ri.cmu.edu/pub_files/pub2/hsiung_p_k_1990_1/hsiung_p_k_1990_1.pdf          │ NULL     │ 138006243 │
│      ·     │                          ·                                                                                             │                     ·                      │     ·            │                     ·                                                                 │  ·       │     ·     │
│      ·     │                          ·                                                                                             │                     ·                      │     ·            │                     ·                                                                 │  ·       │     ·     │
│      ·     │                          ·                                                                                             │                     ·                      │     ·            │                     ·                                                                 │  ·       │     ·     │
│ 2894279555 │ Situ: Identifying and Explaining Suspicious Behavior in Networks                                                       │ https://doi.org/10.1109/tvcg.2018.2865029  │ 2018-08-20       │ https://www.osti.gov/servlets/purl/1486963                                            │ NULL     │ 138006243 │
│ 2896091756 │ Enhancing Web-based Analytics Applications through Provenance                                                          │ https://doi.org/10.1109/tvcg.2018.2865039  │ 2018-10-19       │ None                                                                                  │ NULL     │ 138006243 │
│ 2904955348 │ Futzing and Moseying: Interviews with Professional Data Analysts on Exploration Practices                              │ https://doi.org/10.1109/tvcg.2018.2865040  │ 2018-08-20       │ https://escholarship.org/content/qt04g0z5gn/qt04g0z5gn.pdf?t=pvt8ml                   │ NULL     │ 138006243 │
│ 2888032845 │ ForVizor: Visualizing Spatio-Temporal Team Formations in Soccer                                                        │ https://doi.org/10.1109/tvcg.2018.2865041  │ 2018-08-20       │ None                                                                                  │ NULL     │ 138006243 │
│ 2890529371 │ Identification of Temporally Varying Areas of Interest in Long-Duration Eye-Tracking Data Sets                         │ https://doi.org/10.1109/tvcg.2018.2865042  │ 2018-09-03       │ None                                                                                  │ NULL     │ 138006243 │
│ 2889730816 │ RegressionExplorer: Interactive Exploration of Logistic Regression Models with Subgroup Analysis                       │ https://doi.org/10.1109/tvcg.2018.2865043  │ 2018-09-13       │ https://pure.tue.nl/ws/files/116894719/08464305.pdf                                   │ NULL     │ 138006243 │
│ 2963123635 │ Seq2seq-Vis: A Visual Debugging Tool for Sequence-to-Sequence Models                                                   │ https://doi.org/10.1109/tvcg.2018.2865044  │ 2018-10-17       │ https://arxiv.org/pdf/1804.09299                                                      │ NULL     │ 138006243 │
│ 2888244365 │ SIRIUS: Dual, Symmetric, Interactive Dimension Reductions                                                              │ https://doi.org/10.1109/tvcg.2018.2865047  │ 2018-08-20       │ None                                                                                  │ NULL     │ 138006243 │
│ 2888207115 │ MotionRugs: Visualizing Collective Trends in Space and Time                                                            │ https://doi.org/10.1109/tvcg.2018.2865049  │ 2018-08-20       │ https://kops.uni-konstanz.de/bitstreams/6238ff7a-1096-4aae-8144-4c2cd238c198/download │ NULL     │ 138006243 │
│ 2886794935 │ Drag and Track: A Direct Manipulation Interface for Contextualizing Data Instances within a Continuous Parameter Space │ https://doi.org/10.1109/tvcg.2018.2865051  │ 2018-08-20       │ None                                                                                  │ NULL     │ 138006243 │
├────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────┴──────────────────┴───────────────────────────────────────────────────────────────────────────────────────┴──────────┴───────────┤
│ 3053 rows (20 shown)                                                                                                                                                                                                                                                                                     7 columns │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [5]:
metadata = pd.read_csv("./metadata.csv",header=None,names=["journal","title","doi","link"])

In [6]:
metadata

,journal,title,doi,link
0,Vis,Interdisciplinary visualization: lessons learn...,10.0000/00000002,http://dl.acm.org/citation.cfm?id=949606&CFID=...
1,Vis,Surface representations of two- and three-dime...,10.1109/VISUAL.1990.146359,http://dx.doi.org/10.1109/VISUAL.1990.146359
2,Vis,FAST: a multi-processed environment for visual...,10.1109/VISUAL.1990.146360,http://dx.doi.org/10.1109/VISUAL.1990.146360
3,Vis,The VIS-5D system for easy interactive visuali...,10.1109/VISUAL.1990.146361,http://dx.doi.org/10.1109/VISUAL.1990.146361
4,Vis,A procedural interface for volume rendering,10.1109/VISUAL.1990.146362,http://dx.doi.org/10.1109/VISUAL.1990.146362
...,...,...,...,...
3096,VAST,RegressionExplorer: Interactive Exploration of...,10.1109/TVCG.2018.2865043,http://dx.doi.org/10.1109/TVCG.2018.2865043
3097,VAST,Seq2Seq-Vis: A Visual Debugging Tool for Seque...,10.1109/TVCG.2018.2865044,http://dx.doi.org/10.1109/TVCG.2018.2865044
3098,VAST,"SIRIUS: Dual, Symmetric, Interactive Dimension...",10.1109/TVCG.2018.2865047,http://dx.doi.org/10.1109/TVCG.2018.2865047
3099,VAST,MotionRugs: Visualizing Collective Trends in S...,10.1109/TVCG.2018.2865049,http://dx.doi.org/10.1109/TVCG.2018.2865049
3100,VAST,Drag and Track: A Direct Manipulation Interfac...,10.1109/TVCG.2018.2865051,http://dx.doi.org/10.1109/TVCG.2018.2865051

In [7]:
import numpy as np

In [8]:
dois = metadata[metadata.link.str.contains("doi.org/")].copy()
dois["metadata_index"] = dois.index
dois["database_index"]=np.arange(dois.shape[0])

In [9]:
dois

,journal,title,doi,link,metadata_index,database_index
1,Vis,Surface representations of two- and three-dime...,10.1109/VISUAL.1990.146359,http://dx.doi.org/10.1109/VISUAL.1990.146359,1,0
2,Vis,FAST: a multi-processed environment for visual...,10.1109/VISUAL.1990.146360,http://dx.doi.org/10.1109/VISUAL.1990.146360,2,1
3,Vis,The VIS-5D system for easy interactive visuali...,10.1109/VISUAL.1990.146361,http://dx.doi.org/10.1109/VISUAL.1990.146361,3,2
4,Vis,A procedural interface for volume rendering,10.1109/VISUAL.1990.146362,http://dx.doi.org/10.1109/VISUAL.1990.146362,4,3
5,Vis,Techniques for the interactive visualization o...,10.1109/VISUAL.1990.146363,http://dx.doi.org/10.1109/VISUAL.1990.146363,5,4
...,...,...,...,...,...,...
3096,VAST,RegressionExplorer: Interactive Exploration of...,10.1109/TVCG.2018.2865043,http://dx.doi.org/10.1109/TVCG.2018.2865043,3096,3048
3097,VAST,Seq2Seq-Vis: A Visual Debugging Tool for Seque...,10.1109/TVCG.2018.2865044,http://dx.doi.org/10.1109/TVCG.2018.2865044,3097,3049
3098,VAST,"SIRIUS: Dual, Symmetric, Interactive Dimension...",10.1109/TVCG.2018.2865047,http://dx.doi.org/10.1109/TVCG.2018.2865047,3098,3050
3099,VAST,MotionRugs: Visualizing Collective Trends in S...,10.1109/TVCG.2018.2865049,http://dx.doi.org/10.1109/TVCG.2018.2865049,3099,3051
3100,VAST,Drag and Track: A Direct Manipulation Interfac...,10.1109/TVCG.2018.2865051,http://dx.doi.org/10.1109/TVCG.2018.2865051,3100,3052

In [10]:
import json

In [11]:
from pathlib import Path

In [12]:
annotation_data = json.loads(Path("./annotation.json").read_text())

In [13]:
original_db = db.connect("./original.db")

In [14]:
original_db.sql("SELECT * FROM figure").show()

CatalogException: Catalog Error: Table with name figure does not exist!
Did you mean "pg_attrdef"?

In [15]:
# read an annotation entry,
# find the row in the metadata table it corresponds with, which is 1 the annotation value
# follow the structure for the figure table in the original db

# figure entry needs 3 things, paper id, a local path (will ignore for now), and then a server path following this pattern
# https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1021_0000_0.png
# but note that on the server the number is left padded by zeros which makes things kind of weird

In [16]:
# it appears that I skip the results in here that don't have a visualization associated with them
# otherwise format is {paper_id}_{image_id:left aligned, 4 0s padded}_{bbox_list_index:no padding or alignment}

annotation_paper_id = 1021
annotation_data[str(annotation_paper_id)]



# iterate over the images for this record


metadata_row = metadata.iloc[annotation_paper_id]
metadata_row

metadata_row.title

# keep in mind that for now the visimages database doesn't include things that didn't have a nice doi, so we can't map directly to the table entry number, we have to base on titles



visimages_entry = visimages.sql(f"SELECT * FROM paper WHERE title like '{metadata_row.title}'")

so the process should be like this,
for each paper key we
then we also get a row from the metadata
we then also get the paper_id using a WHERE clause on that metadata rows' title
then we 
iterate over the images
each one we check whether there's a vbox, if so we iterate over them
then we construct a subfigure url, this contains the paper id, the image id, and then the index of the bbox 
for each one we store the subfigure url, the subfigure id, the paper id, and also additional attributes that may be of interest to the subfigure (chart type associated with it), caption information,

In [17]:
visimages.sql("SELECT * FROM paper WHERE title like 'Keynote*'").show()

┌───────┬─────────┬─────────┬──────────────────┬─────────┬──────────┬─────────┐
│  id   │  title  │   doi   │ publication_date │ oa_url  │ pdf_path │ inst_id │
│ int64 │ varchar │ varchar │       date       │ varchar │ varchar  │  int64  │
├───────┴─────────┴─────────┴──────────────────┴─────────┴──────────┴─────────┤
│                                   0 rows                                    │
└─────────────────────────────────────────────────────────────────────────────┘

In [18]:
import numpy as np

In [19]:
dois

,journal,title,doi,link,metadata_index,database_index
1,Vis,Surface representations of two- and three-dime...,10.1109/VISUAL.1990.146359,http://dx.doi.org/10.1109/VISUAL.1990.146359,1,0
2,Vis,FAST: a multi-processed environment for visual...,10.1109/VISUAL.1990.146360,http://dx.doi.org/10.1109/VISUAL.1990.146360,2,1
3,Vis,The VIS-5D system for easy interactive visuali...,10.1109/VISUAL.1990.146361,http://dx.doi.org/10.1109/VISUAL.1990.146361,3,2
4,Vis,A procedural interface for volume rendering,10.1109/VISUAL.1990.146362,http://dx.doi.org/10.1109/VISUAL.1990.146362,4,3
5,Vis,Techniques for the interactive visualization o...,10.1109/VISUAL.1990.146363,http://dx.doi.org/10.1109/VISUAL.1990.146363,5,4
...,...,...,...,...,...,...
3096,VAST,RegressionExplorer: Interactive Exploration of...,10.1109/TVCG.2018.2865043,http://dx.doi.org/10.1109/TVCG.2018.2865043,3096,3048
3097,VAST,Seq2Seq-Vis: A Visual Debugging Tool for Seque...,10.1109/TVCG.2018.2865044,http://dx.doi.org/10.1109/TVCG.2018.2865044,3097,3049
3098,VAST,"SIRIUS: Dual, Symmetric, Interactive Dimension...",10.1109/TVCG.2018.2865047,http://dx.doi.org/10.1109/TVCG.2018.2865047,3098,3050
3099,VAST,MotionRugs: Visualizing Collective Trends in S...,10.1109/TVCG.2018.2865049,http://dx.doi.org/10.1109/TVCG.2018.2865049,3099,3051
3100,VAST,Drag and Track: A Direct Manipulation Interfac...,10.1109/TVCG.2018.2865051,http://dx.doi.org/10.1109/TVCG.2018.2865051,3100,3052

In [20]:
index_map= {r.metadata_index:r.database_index for i,r in dois.iterrows()}

In [21]:
index_map

{1: 0,
 2: 1,
 3: 2,
 4: 3,
 5: 4,
 6: 5,
 7: 6,
 8: 7,
 9: 8,
 10: 9,
 11: 10,
 12: 11,
 13: 12,
 14: 13,
 15: 14,
 16: 15,
 17: 16,
 18: 17,
 19: 18,
 20: 19,
 21: 20,
 22: 21,
 23: 22,
 24: 23,
 25: 24,
 26: 25,
 27: 26,
 28: 27,
 29: 28,
 30: 29,
 31: 30,
 32: 31,
 33: 32,
 34: 33,
 35: 34,
 36: 35,
 37: 36,
 38: 37,
 39: 38,
 40: 39,
 41: 40,
 42: 41,
 43: 42,
 44: 43,
 45: 44,
 46: 45,
 47: 46,
 48: 47,
 49: 48,
 50: 49,
 51: 50,
 52: 51,
 53: 52,
 54: 53,
 55: 54,
 56: 55,
 57: 56,
 58: 57,
 59: 58,
 60: 59,
 61: 60,
 62: 61,
 63: 62,
 64: 63,
 65: 64,
 66: 65,
 67: 66,
 68: 67,
 69: 68,
 70: 69,
 71: 70,
 72: 71,
 73: 72,
 74: 73,
 75: 74,
 76: 75,
 77: 76,
 78: 77,
 79: 78,
 80: 79,
 81: 80,
 82: 81,
 83: 82,
 84: 83,
 85: 84,
 86: 85,
 87: 86,
 88: 87,
 89: 88,
 90: 89,
 91: 90,
 92: 91,
 93: 92,
 94: 93,
 95: 94,
 96: 95,
 97: 96,
 98: 97,
 99: 98,
 100: 99,
 101: 100,
 102: 101,
 103: 102,
 104: 103,
 105: 104,
 106: 105,
 107: 106,
 108: 107,
 109: 108,
 110: 109,
 111: 110,
 112: 111,
 113: 112,
 114: 113,
 115: 114,
 116: 115,
 117: 116,
 118: 117,
 119: 118,
 120: 119,
 121: 120,
 122: 121,
 123: 122,
 124: 123,
 125: 124,
 126: 125,
 127: 126,
 128: 127,
 129: 128,
 130: 129,
 131: 130,
 132: 131,
 133: 132,
 134: 133,
 135: 134,
 136: 135,
 137: 136,
 138: 137,
 139: 138,
 140: 139,
 141: 140,
 142: 141,
 143: 142,
 144: 143,
 145: 144,
 146: 145,
 147: 146,
 148: 147,
 149: 148,
 150: 149,
 151: 150,
 152: 151,
 153: 152,
 154: 153,
 155: 154,
 156: 155,
 157: 156,
 158: 157,
 159: 158,
 160: 159,
 161: 160,
 162: 161,
 163: 162,
 164: 163,
 165: 164,
 166: 165,
 167: 166,
 168: 167,
 169: 168,
 170: 169,
 171: 170,
 172: 171,
 173: 172,
 174: 173,
 175: 174,
 176: 175,
 177: 176,
 178: 177,
 179: 178,
 180: 179,
 181: 180,
 182: 181,
 183: 182,
 184: 183,
 185: 184,
 186: 185,
 187: 186,
 188: 187,
 189: 188,
 190: 189,
 191: 190,
 192: 191,
 193: 192,
 194: 193,
 195: 194,
 196: 195,
 197: 196,
 198: 197,
 199: 198,
 200: 199,
 201: 200,
 202: 201,
 203: 202,
 204: 203,
 205: 204,
 206: 205,
 207: 206,
 208: 207,
 209: 208,
 210: 209,
 211: 210,
 212: 211,
 213: 212,
 214: 213,
 215: 214,
 216: 215,
 217: 216,
 218: 217,
 219: 218,
 220: 219,
 221: 220,
 222: 221,
 223: 222,
 224: 223,
 225: 224,
 226: 225,
 227: 226,
 228: 227,
 229: 228,
 230: 229,
 231: 230,
 232: 231,
 233: 232,
 234: 233,
 235: 234,
 236: 235,
 237: 236,
 238: 237,
 239: 238,
 240: 239,
 241: 240,
 242: 241,
 243: 242,
 244: 243,
 245: 244,
 246: 245,
 247: 246,
 248: 247,
 249: 248,
 250: 249,
 251: 250,
 252: 251,
 253: 252,
 254: 253,
 255: 254,
 256: 255,
 257: 256,
 258: 257,
 259: 258,
 260: 259,
 261: 260,
 262: 261,
 263: 262,
 264: 263,
 265: 264,
 266: 265,
 267: 266,
 268: 267,
 269: 268,
 270: 269,
 271: 270,
 272: 271,
 273: 272,
 274: 273,
 275: 274,
 276: 275,
 277: 276,
 278: 277,
 279: 278,
 280: 279,
 281: 280,
 282: 281,
 283: 282,
 284: 283,
 285: 284,
 286: 285,
 287: 286,
 288: 287,
 289: 288,
 290: 289,
 291: 290,
 292: 291,
 293: 292,
 294: 293,
 295: 294,
 296: 295,
 297: 296,
 298: 297,
 299: 298,
 300: 299,
 301: 300,
 302: 301,
 303: 302,
 304: 303,
 305: 304,
 306: 305,
 307: 306,
 308: 307,
 309: 308,
 310: 309,
 311: 310,
 312: 311,
 313: 312,
 314: 313,
 315: 314,
 316: 315,
 317: 316,
 318: 317,
 319: 318,
 320: 319,
 321: 320,
 322: 321,
 323: 322,
 324: 323,
 325: 324,
 326: 325,
 327: 326,
 328: 327,
 329: 328,
 330: 329,
 331: 330,
 332: 331,
 333: 332,
 334: 333,
 335: 334,
 336: 335,
 337: 336,
 338: 337,
 339: 338,
 340: 339,
 341: 340,
 342: 341,
 343: 342,
 344: 343,
 345: 344,
 346: 345,
 347: 346,
 348: 347,
 349: 348,
 350: 349,
 351: 350,
 352: 351,
 353: 352,
 354: 353,
 355: 354,
 356: 355,
 357: 356,
 358: 357,
 359: 358,
 360: 359,
 361: 360,
 362: 361,
 363: 362,
 364: 363,
 365: 364,
 366: 365,
 367: 366,
 368: 367,
 369: 368,
 370: 369,
 371: 370,
 372: 371,
 373: 372,
 374: 373,
 375: 374,
 376: 375,
 377: 376,
 378: 377,
 379: 378,
 380: 379,
 381: 380,
 382: 381,
 384: 382,
 385: 383,
 386: 384,
 389: 385,
 390: 386,
 391: 387,
 392: 388,
 393: 389,
 394: 390,
 395: 391,
 396: 392,
 397: 393,
 398: 394,
 399: 395,
 400: 396,
 401: 397,
 402: 398,
 403: 399,
 404: 400,
 405: 401,
 406: 402,
 408: 403,
 409: 404,
 410: 405,
 411: 406,
 413: 407,
 416: 408,
 417: 409,
 418: 410,
 419: 411,
 420: 412,
 421: 413,
 422: 414,
 423: 415,
 425: 416,
 426: 417,
 427: 418,
 428: 419,
 429: 420,
 430: 421,
 431: 422,
 432: 423,
 433: 424,
 435: 425,
 436: 426,
 437: 427,
 438: 428,
 439: 429,
 440: 430,
 442: 431,
 443: 432,
 444: 433,
 445: 434,
 446: 435,
 447: 436,
 448: 437,
 449: 438,
 450: 439,
 451: 440,
 452: 441,
 453: 442,
 454: 443,
 455: 444,
 456: 445,
 457: 446,
 458: 447,
 459: 448,
 460: 449,
 461: 450,
 462: 451,
 463: 452,
 464: 453,
 465: 454,
 466: 455,
 467: 456,
 468: 457,
 469: 458,
 470: 459,
 471: 460,
 472: 461,
 473: 462,
 474: 463,
 475: 464,
 476: 465,
 477: 466,
 478: 467,
 479: 468,
 480: 469,
 481: 470,
 482: 471,
 483: 472,
 484: 473,
 485: 474,
 486: 475,
 487: 476,
 488: 477,
 489: 478,
 490: 479,
 491: 480,
 492: 481,
 493: 482,
 494: 483,
 495: 484,
 496: 485,
 497: 486,
 498: 487,
 499: 488,
 500: 489,
 501: 490,
 502: 491,
 503: 492,
 504: 493,
 505: 494,
 506: 495,
 507: 496,
 508: 497,
 509: 498,
 510: 499,
 511: 500,
 512: 501,
 513: 502,
 514: 503,
 515: 504,
 516: 505,
 517: 506,
 518: 507,
 519: 508,
 520: 509,
 521: 510,
 522: 511,
 523: 512,
 524: 513,
 525: 514,
 526: 515,
 527: 516,
 528: 517,
 529: 518,
 530: 519,
 531: 520,
 532: 521,
 533: 522,
 534: 523,
 535: 524,
 536: 525,
 537: 526,
 538: 527,
 539: 528,
 540: 529,
 541: 530,
 542: 531,
 543: 532,
 544: 533,
 545: 534,
 546: 535,
 547: 536,
 548: 537,
 549: 538,
 550: 539,
 551: 540,
 552: 541,
 553: 542,
 554: 543,
 555: 544,
 556: 545,
 557: 546,
 558: 547,
 559: 548,
 560: 549,
 561: 550,
 562: 551,
 563: 552,
 564: 553,
 565: 554,
 566: 555,
 567: 556,
 568: 557,
 569: 558,
 570: 559,
 571: 560,
 572: 561,
 573: 562,
 574: 563,
 575: 564,
 576: 565,
 577: 566,
 578: 567,
 579: 568,
 580: 569,
 581: 570,
 582: 571,
 583: 572,
 584: 573,
 585: 574,
 586: 575,
 587: 576,
 588: 577,
 589: 578,
 590: 579,
 591: 580,
 592: 581,
 593: 582,
 594: 583,
 595: 584,
 596: 585,
 597: 586,
 598: 587,
 599: 588,
 600: 589,
 601: 590,
 602: 591,
 603: 592,
 604: 593,
 605: 594,
 606: 595,
 607: 596,
 608: 597,
 609: 598,
 610: 599,
 611: 600,
 612: 601,
 613: 602,
 614: 603,
 615: 604,
 616: 605,
 617: 606,
 618: 607,
 619: 608,
 620: 609,
 621: 610,
 622: 611,
 623: 612,
 624: 613,
 625: 614,
 626: 615,
 627: 616,
 628: 617,
 629: 618,
 630: 619,
 631: 620,
 632: 621,
 633: 622,
 634: 623,
 635: 624,
 636: 625,
 637: 626,
 638: 627,
 639: 628,
 640: 629,
 641: 630,
 642: 631,
 643: 632,
 644: 633,
 645: 634,
 646: 635,
 647: 636,
 648: 637,
 649: 638,
 650: 639,
 652: 640,
 653: 641,
 654: 642,
 655: 643,
 657: 644,
 658: 645,
 659: 646,
 660: 647,
 661: 648,
 662: 649,
 663: 650,
 665: 651,
 666: 652,
 667: 653,
 668: 654,
 669: 655,
 670: 656,
 671: 657,
 672: 658,
 673: 659,
 674: 660,
 675: 661,
 676: 662,
 677: 663,
 678: 664,
 679: 665,
 680: 666,
 682: 667,
 683: 668,
 684: 669,
 685: 670,
 686: 671,
 687: 672,
 688: 673,
 689: 674,
 690: 675,
 691: 676,
 692: 677,
 695: 678,
 696: 679,
 697: 680,
 698: 681,
 699: 682,
 700: 683,
 701: 684,
 702: 685,
 703: 686,
 704: 687,
 705: 688,
 706: 689,
 707: 690,
 708: 691,
 709: 692,
 710: 693,
 711: 694,
 712: 695,
 713: 696,
 714: 697,
 715: 698,
 716: 699,
 717: 700,
 718: 701,
 720: 702,
 721: 703,
 722: 704,
 724: 705,
 725: 706,
 726: 707,
 727: 708,
 728: 709,
 729: 710,
 730: 711,
 731: 712,
 732: 713,
 733: 714,
 734: 715,
 735: 716,
 736: 717,
 737: 718,
 738: 719,
 739: 720,
 740: 721,
 741: 722,
 742: 723,
 743: 724,
 744: 725,
 745: 726,
 746: 727,
 748: 728,
 749: 729,
 750: 730,
 751: 731,
 752: 732,
 753: 733,
 754: 734,
 755: 735,
 756: 736,
 757: 737,
 758: 738,
 759: 739,
 760: 740,
 761: 741,
 762: 742,
 764: 743,
 765: 744,
 766: 745,
 767: 746,
 768: 747,
 769: 748,
 770: 749,
 771: 750,
 773: 751,
 774: 752,
 775: 753,
 776: 754,
 777: 755,
 778: 756,
 779: 757,
 780: 758,
 781: 759,
 782: 760,
 784: 761,
 786: 762,
 787: 763,
 788: 764,
 789: 765,
 791: 766,
 794: 767,
 795: 768,
 796: 769,
 797: 770,
 798: 771,
 799: 772,
 800: 773,
 801: 774,
 802: 775,
 803: 776,
 804: 777,
 805: 778,
 806: 779,
 807: 780,
 808: 781,
 809: 782,
 810: 783,
 811: 784,
 812: 785,
 813: 786,
 815: 787,
 816: 788,
 817: 789,
 818: 790,
 819: 791,
 820: 792,
 821: 793,
 822: 794,
 823: 795,
 824: 796,
 825: 797,
 826: 798,
 827: 799,
 828: 800,
 829: 801,
 830: 802,
 831: 803,
 832: 804,
 833: 805,
 834: 806,
 835: 807,
 836: 808,
 837: 809,
 838: 810,
 839: 811,
 840: 812,
 841: 813,
 842: 814,
 845: 815,
 848: 816,
 849: 817,
 850: 818,
 851: 819,
 852: 820,
 853: 821,
 855: 822,
 856: 823,
 857: 824,
 858: 825,
 859: 826,
 861: 827,
 862: 828,
 863: 829,
 864: 830,
 865: 831,
 866: 832,
 867: 833,
 868: 834,
 869: 835,
 870: 836,
 872: 837,
 873: 838,
 874: 839,
 875: 840,
 876: 841,
 877: 842,
 879: 843,
 880: 844,
 881: 845,
 882: 846,
 883: 847,
 884: 848,
 885: 849,
 886: 850,
 888: 851,
 889: 852,
 890: 853,
 892: 854,
 893: 855,
 894: 856,
 895: 857,
 896: 858,
 897: 859,
 898: 860,
 899: 861,
 900: 862,
 901: 863,
 902: 864,
 903: 865,
 904: 866,
 905: 867,
 906: 868,
 907: 869,
 908: 870,
 911: 871,
 913: 872,
 914: 873,
 915: 874,
 916: 875,
 917: 876,
 918: 877,
 919: 878,
 920: 879,
 921: 880,
 922: 881,
 923: 882,
 924: 883,
 925: 884,
 926: 885,
 927: 886,
 928: 887,
 929: 888,
 930: 889,
 931: 890,
 932: 891,
 933: 892,
 934: 893,
 935: 894,
 936: 895,
 937: 896,
 938: 897,
 939: 898,
 940: 899,
 941: 900,
 942: 901,
 943: 902,
 944: 903,
 945: 904,
 946: 905,
 947: 906,
 948: 907,
 949: 908,
 950: 909,
 951: 910,
 952: 911,
 953: 912,
 954: 913,
 955: 914,
 956: 915,
 957: 916,
 958: 917,
 959: 918,
 960: 919,
 961: 920,
 962: 921,
 963: 922,
 964: 923,
 965: 924,
 966: 925,
 967: 926,
 968: 927,
 969: 928,
 970: 929,
 971: 930,
 972: 931,
 973: 932,
 974: 933,
 975: 934,
 976: 935,
 977: 936,
 978: 937,
 979: 938,
 980: 939,
 981: 940,
 982: 941,
 983: 942,
 984: 943,
 985: 944,
 986: 945,
 987: 946,
 988: 947,
 989: 948,
 990: 949,
 991: 950,
 992: 951,
 993: 952,
 994: 953,
 995: 954,
 996: 955,
 997: 956,
 998: 957,
 999: 958,
 1000: 959,
 1001: 960,
 1002: 961,
 1003: 962,
 1004: 963,
 1005: 964,
 1006: 965,
 1007: 966,
 1008: 967,
 1009: 968,
 1010: 969,
 1011: 970,
 1012: 971,
 1013: 972,
 1014: 973,
 1015: 974,
 1016: 975,
 1017: 976,
 1018: 977,
 1019: 978,
 1020: 979,
 1021: 980,
 1022: 981,
 1023: 982,
 1024: 983,
 1025: 984,
 1026: 985,
 1027: 986,
 1030: 987,
 1031: 988,
 1032: 989,
 1033: 990,
 1035: 991,
 1036: 992,
 1037: 993,
 1038: 994,
 1039: 995,
 1040: 996,
 1041: 997,
 1042: 998,
 1043: 999,
 ...}

In [22]:
import tqdm

In [23]:
# it appears that I skip the results in here that don't have a visualization associated with them
# otherwise format is {paper_id}_{image_id:left aligned, 4 0s padded}_{bbox_list_index:no padding or alignment}
results = []
stop = False
for annotation_paper_id in tqdm.tqdm(annotation_data):
    # iterate over the images for this record
    # only expect one result so take the 0th
    doi_index = index_map.get(int(annotation_paper_id),-1)
    if doi_index == -1:
        # print("missing",annotation_paper_id)
        continue
    # print(doi_index)
    dois_row = dois.iloc[doi_index]
    
    
    
    paper_title = dois_row.title
    # print(paper_title)
    # get the row from the database this corresponds to
    database_index = int(dois_row.database_index)
    # print(database_index,paper_title)
    visimages_entry = visimages.sql(f"SELECT * from paper OFFSET {database_index} LIMIT 1")

    paper_annotation = annotation_data[str(annotation_paper_id)]
    for im in paper_annotation:
        # keys are 
        vbbox=im["visualization_bbox"]
        im_id = im["image_id"]
        caption = im["caption"]
        if len(vbbox)==0:
            continue
        else:
            # iterate over the charts
            index = 0
            
            for chart_type,charts in vbbox.items():
                for c in charts:
                    # add a row to the results for each of these
                    # increment the index
                    url = f"https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/{annotation_paper_id}_{im_id:<04d}_{index}.png"
                    index+=1
                    
                    results.append(dict(
                        paper_id=visimages_entry.id.fetchone()[0],
                        server_path=url,
                        caption=caption,
                        chart_type=chart_type
                    ))
            
results

100%|███████████████████████████████████████| 1395/1395 [00:41<00:00, 33.90it/s]

[{'paper_id': 2165915693,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1021_0000_0.png',
  'caption': 'Figure 2: u, w space diagram',
  'chart_type': 'line_chart'},
 {'paper_id': 2165915693,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1021_2000_0.png',
  'caption': 'Figure 1: World space and image space',
  'chart_type': 'line_chart'},
 {'paper_id': 2165915693,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1021_3000_0.png',
  'caption': 'Figure 3: Metric in (u, w) space',
  'chart_type': 'line_chart'},
 {'paper_id': 2165915693,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1021_3000_1.png',
  'caption': 'Figure 3: Metric in (u, w) space',
  'chart_type': 'line_chart'},
 {'paper_id': 2165915693,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1021_3000_2.png',
  'caption': 'Figure 3: Metric in (u, w) space',
  'chart_type': 'line_chart'},
 {'paper_id': 2165915693,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1021_5000_0.png',
  'caption': 'Figure 5: Paths and iso-distance curves in (u, w) space',
  'chart_type': 'scatterplot'},
 {'paper_id': 2165915693,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1021_5000_1.png',
  'caption': 'Figure 5: Paths and iso-distance curves in (u, w) space',
  'chart_type': 'scatterplot'},
 {'paper_id': 2165915693,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1021_5000_2.png',
  'caption': 'Figure 5: Paths and iso-distance curves in (u, w) space',
  'chart_type': 'scatterplot'},
 {'paper_id': 2165915693,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1021_6000_0.png',
  'caption': 'Figure 6: u and w as a function of s',
  'chart_type': 'line_chart'},
 {'paper_id': 2165915693,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1021_7000_0.png',
  'caption': 'Figure 7: Scatterplot of V and ρ values found',
  'chart_type': 'scatterplot'},
 {'paper_id': 2116787255,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1022_6000_0.png',
  'caption': 'Figure 7. The linked structures in L- for the entire Dr. Seuss image are shown in orange.',
  'chart_type': 'tree'},
 {'paper_id': 2116787255,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1022_6000_1.png',
  'caption': 'Figure 7. The linked structures in L- for the entire Dr. Seuss image are shown in orange.',
  'chart_type': 'tree'},
 {'paper_id': 2116787255,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1022_7000_0.png',
  'caption': 'Figure 6. Linked segments in L- at different scales for part of the Dr. Seuss image.',
  'chart_type': 'tree'},
 {'paper_id': 2116787255,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1022_8000_0.png',
  'caption': 'Figure 9. Gestalt cartoons showing differentiation of figure and ground in a graph. Left: thin grid lines. Right: thick grid lines.',
  'chart_type': 'line_chart'},
 {'paper_id': 2116787255,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1022_8000_1.png',
  'caption': 'Figure 9. Gestalt cartoons showing differentiation of figure and ground in a graph. Left: thin grid lines. Right: thick grid lines.',
  'chart_type': 'line_chart'},
 {'paper_id': 2116787255,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1022_8000_2.png',
  'caption': 'Figure 9. Gestalt cartoons showing differentiation of figure and ground in a graph. Left: thin grid lines. Right: thick grid lines.',
  'chart_type': 'line_chart'},
 {'paper_id': 2116787255,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1022_8000_3.png',
  'caption': 'Figure 9. Gestalt cartoons showing differentiation of figure and ground in a graph. Left: thin grid lines. Right: thick grid lines.',
  'chart_type': 'line_chart'},
 {'paper_id': 2116787255,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1022_9000_0.png',
  'caption': 'Figure 10. Original image and gestalt cartoons of the Hertzprung Russell diagram.',
  'chart_type': 'heatmap'},
 {'paper_id': 2116787255,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1022_9000_1.png',
  'caption': 'Figure 10. Original image and gestalt cartoons of the Hertzprung Russell diagram.',
  'chart_type': 'heatmap'},
 {'paper_id': 2116787255,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1022_9000_2.png',
  'caption': 'Figure 10. Original image and gestalt cartoons of the Hertzprung Russell diagram.',
  'chart_type': 'heatmap'},
 {'paper_id': 2116787255,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1022_9000_3.png',
  'caption': 'Figure 10. Original image and gestalt cartoons of the Hertzprung Russell diagram.',
  'chart_type': 'heatmap'},
 {'paper_id': 2116787255,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1022_9000_4.png',
  'caption': 'Figure 10. Original image and gestalt cartoons of the Hertzprung Russell diagram.',
  'chart_type': 'scatterplot'},
 {'paper_id': 2116787255,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1022_9000_5.png',
  'caption': 'Figure 10. Original image and gestalt cartoons of the Hertzprung Russell diagram.',
  'chart_type': 'scatterplot'},
 {'paper_id': 2116787255,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1022_9000_6.png',
  'caption': 'Figure 10. Original image and gestalt cartoons of the Hertzprung Russell diagram.',
  'chart_type': 'scatterplot'},
 {'paper_id': 2116787255,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1022_9000_7.png',
  'caption': 'Figure 10. Original image and gestalt cartoons of the Hertzprung Russell diagram.',
  'chart_type': 'scatterplot'},
 {'paper_id': 2116787255,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1022_1000_0.png',
  'caption': 'Figure 12. Left: sketch of portion of Market Map. Right: A redesign with stronger borders.',
  'chart_type': 'treemap'},
 {'paper_id': 2116787255,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1022_1000_1.png',
  'caption': 'Figure 12. Left: sketch of portion of Market Map. Right: A redesign with stronger borders.',
  'chart_type': 'treemap'},
 {'paper_id': 2116787255,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1022_1100_0.png',
  'caption': 'Figure 14. L+ structure of redesigned map. Grouping is almost perfect; only flaw is an “orphan” item at A.',
  'chart_type': 'tree'},
 {'paper_id': 2116787255,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1022_1200_0.png',
  'caption': 'Figure 13. L+ structure of original map design at scales up to s=20. Some flaws: A, two items in different groups are spuriously joined; B and C, a single group is spuriously separated.',
  'chart_type': 'tree'},
 {'paper_id': 2116787255,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1022_1300_0.png',
  'caption': 'Figure 11. Human expert partitioning of HR diagram. After [Fix 1999].',
  'chart_type': 'scatterplot'},
 {'paper_id': 1487235154,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1023_0000_0.png',
  'caption': 'Figure 1. GeoVISTA Studio component-based architecture',
  'chart_type': 'graph'},
 {'paper_id': 1487235154,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1023_1000_0.png',
  'caption': 'Figure 2. GeoVISTA Studio application design',
  'chart_type': 'graph'},
 {'paper_id': 1487235154,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1023_2000_0.png',
  'caption': 'Figure 3. MultiForm Small Multiple with scatterplot and map.',
  'chart_type': 'heatmap'},
 {'paper_id': 1487235154,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1023_2000_1.png',
  'caption': 'Figure 3. MultiForm Small Multiple with scatterplot and map.',
  'chart_type': 'heatmap'},
 {'paper_id': 1487235154,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1023_2000_2.png',
  'caption': 'Figure 3. MultiForm Small Multiple with scatterplot and map.',
  'chart_type': 'heatmap'},
 {'paper_id': 1487235154,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1023_2000_3.png',
  'caption': 'Figure 3. MultiForm Small Multiple with scatterplot and map.',
  'chart_type': 'heatmap'},
 {'paper_id': 1487235154,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1023_2000_4.png',
  'caption': 'Figure 3. MultiForm Small Multiple with scatterplot and map.',
  'chart_type': 'scatterplot'},
 {'paper_id': 1487235154,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1023_2000_5.png',
  'caption': 'Figure 3. MultiForm Small Multiple with scatterplot and map.',
  'chart_type': 'scatterplot'},
 {'paper_id': 1487235154,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1023_2000_6.png',
  'caption': 'Figure 3. MultiForm Small Multiple with scatterplot and map.',
  'chart_type': 'map'},
 {'paper_id': 1487235154,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1023_2000_7.png',
  'caption': 'Figure 3. MultiForm Small Multiple with scatterplot and map.',
  'chart_type': 'map'},
 {'paper_id': 1487235154,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1023_3000_0.png',
  'caption': 'Figure 4. Typical display. MultiForm Bivariate Matrix with map and scatterplot(left), univariate map(lower right), conditioning picker and sliders generated by user selection (middle right), and conditioning animator (top right). An additive selection has been made in lower right scatterplot.',
  'chart_type': 'bar_chart'},
 {'paper_id': 1487235154,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1023_3000_1.png',
  'caption': 'Figure 4. Typical display. MultiForm Bivariate Matrix with map and scatterplot(left), univariate map(lower right), conditioning picker and sliders generated by user selection (middle right), and conditioning animator (top right). An additive selection has been made in lower right scatterplot.',
  'chart_type': 'bar_chart'},
 {'paper_id': 1487235154,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1023_3000_2.png',
  'caption': 'Figure 4. Typical display. MultiForm Bivariate Matrix with map and scatterplot(left), univariate map(lower right), conditioning picker and sliders generated by user selection (middle right), and conditioning animator (top right). An additive selection has been made in lower right scatterplot.',
  'chart_type': 'bar_chart'},
 {'paper_id': 1487235154,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1023_3000_3.png',
  'caption': 'Figure 4. Typical display. MultiForm Bivariate Matrix with map and scatterplot(left), univariate map(lower right), conditioning picker and sliders generated by user selection (middle right), and conditioning animator (top right). An additive selection has been made in lower right scatterplot.',
  'chart_type': 'scatterplot'},
 {'paper_id': 1487235154,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1023_3000_4.png',
  'caption': 'Figure 4. Typical display. MultiForm Bivariate Matrix with map and scatterplot(left), univariate map(lower right), conditioning picker and sliders generated by user selection (middle right), and conditioning animator (top right). An additive selection has been made in lower right scatterplot.',
  'chart_type': 'scatterplot'},
 {'paper_id': 1487235154,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1023_3000_5.png',
  'caption': 'Figure 4. Typical display. MultiForm Bivariate Matrix with map and scatterplot(left), univariate map(lower right), conditioning picker and sliders generated by user selection (middle right), and conditioning animator (top right). An additive selection has been made in lower right scatterplot.',
  'chart_type': 'scatterplot'},
 {'paper_id': 1487235154,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1023_3000_6.png',
  'caption': 'Figure 4. Typical display. MultiForm Bivariate Matrix with map and scatterplot(left), univariate map(lower right), conditioning picker and sliders generated by user selection (middle right), and conditioning animator (top right). An additive selection has been made in lower right scatterplot.',
  'chart_type': 'small_multiple'},
 {'paper_id': 1487235154,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1023_3000_7.png',
  'caption': 'Figure 4. Typical display. MultiForm Bivariate Matrix with map and scatterplot(left), univariate map(lower right), conditioning picker and sliders generated by user selection (middle right), and conditioning animator (top right). An additive selection has been made in lower right scatterplot.',
  'chart_type': 'map'},
 {'paper_id': 1487235154,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1023_3000_8.png',
  'caption': 'Figure 4. Typical display. MultiForm Bivariate Matrix with map and scatterplot(left), univariate map(lower right), conditioning picker and sliders generated by user selection (middle right), and conditioning animator (top right). An additive selection has been made in lower right scatterplot.',
  'chart_type': 'map'},
 {'paper_id': 1487235154,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1023_3000_9.png',
  'caption': 'Figure 4. Typical display. MultiForm Bivariate Matrix with map and scatterplot(left), univariate map(lower right), conditioning picker and sliders generated by user selection (middle right), and conditioning animator (top right). An additive selection has been made in lower right scatterplot.',
  'chart_type': 'map'},
 {'paper_id': 1487235154,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1023_3000_10.png',
  'caption': 'Figure 4. Typical display. MultiForm Bivariate Matrix with map and scatterplot(left), univariate map(lower right), conditioning picker and sliders generated by user selection (middle right), and conditioning animator (top right). An additive selection has been made in lower right scatterplot.',
  'chart_type': 'map'},
 {'paper_id': 1487235154,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1023_4000_0.png',
  'caption': 'Figure 5. Dimension selection tool. Conditional entropy values (below diagonal) and correlation values (abobe diagonal).',
  'chart_type': 'heatmap'},
 {'paper_id': 1487235154,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1023_4000_1.png',
  'caption': 'Figure 5. Dimension selection tool. Conditional entropy values (below diagonal) and correlation values (abobe diagonal).',
  'chart_type': 'matrix'},
 {'paper_id': 1487235154,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1023_5000_0.png',
  'caption': 'Figure 6. Matrix with bivariate map and spacefill components (univariate maps along the diagonal). Counties with a doctor ratio under about 80/1000 are highlighted in the popup scatter-plot -with highlighting propagated to other views.',
  'chart_type': 'heatmap'},
 {'paper_id': 1487235154,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1023_5000_1.png',
  'caption': 'Figure 6. Matrix with bivariate map and spacefill components (univariate maps along the diagonal). Counties with a doctor ratio under about 80/1000 are highlighted in the popup scatter-plot -with highlighting propagated to other views.',
  'chart_type': 'heatmap'},
 {'paper_id': 1487235154,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1023_5000_2.png',
  'caption': 'Figure 6. Matrix with bivariate map and spacefill components (univariate maps along the diagonal). Counties with a doctor ratio under about 80/1000 are highlighted in the popup scatter-plot -with highlighting propagated to other views.',
  'chart_type': 'heatmap'},
 {'paper_id': 1487235154,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1023_5000_3.png',
  'caption': 'Figure 6. Matrix with bivariate map and spacefill components (univariate maps along the diagonal). Counties with a doctor ratio under about 80/1000 are highlighted in the popup scatter-plot -with highlighting propagated to other views.',
  'chart_type': 'matrix'},
 {'paper_id': 1487235154,
  'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1023_5000_4.png',

In [24]:
figures_df = pd.DataFrame(results)

In [25]:
visimages.sql("DROP TABLE figure")

In [26]:
visimages.sql("CREATE TABLE figure AS SELECT * FROM figures_df")

In [27]:
visimages.sql("SELECT * from figure")

┌────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────┐
│  paper_id  │                                                        server_path                                                         │                                                        caption                                                        │         chart_type         │
│   int64    │                                                          varchar                                                           │                                                        varchar                                                        │          varchar           │
├────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────┤
│ 2165915693 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1021_0000_0.png │ Figure 2: u, w space diagram                                                                                          │ line_chart                 │
│ 2165915693 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1021_2000_0.png │ Figure 1: World space and image space                                                                                 │ line_chart                 │
│ 2165915693 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1021_3000_0.png │ Figure 3: Metric in (u, w) space                                                                                      │ line_chart                 │
│ 2165915693 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1021_3000_1.png │ Figure 3: Metric in (u, w) space                                                                                      │ line_chart                 │
│ 2165915693 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1021_3000_2.png │ Figure 3: Metric in (u, w) space                                                                                      │ line_chart                 │
│ 2165915693 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1021_5000_0.png │ Figure 5: Paths and iso-distance curves in (u, w) space                                                               │ scatterplot                │
│ 2165915693 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1021_5000_1.png │ Figure 5: Paths and iso-distance curves in (u, w) space                                                               │ scatterplot                │
│ 2165915693 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1021_5000_2.png │ Figure 5: Paths and iso-distance curves in (u, w) space                                                               │ scatterplot                │
│ 2165915693 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1021_6000_0.png │ Figure 6: u and w as a function of s                                                                                  │ line_chart                 │
│ 2165915693 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1021_7000_0.png │ Figure 7: Scatterplot of V and ρ values found                                                                         │ scatterplot                │
│      ·     │                                                             ·                                                              │                       ·                                                                                               │   ·                        │
│      ·     │                                                             ·                                                              │                       ·                                                                                               │   ·                        │
│      ·     │                                                             ·                                                              │                       ·                                                                                               │   ·                        │
│ 2156473689 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/2101_4000_1.png │ Fig. 5. Bundled ﬂight trails (a). Attribute-based MoleView lens for three altitude levels (b-d)                       │ graph                      │
│ 2156473689 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/2101_4000_2.png │ Fig. 5. Bundled ﬂight trails (a). Attribute-based MoleView lens for three altitude levels (b-d)                       │ graph                      │
│ 2156473689 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/2101_4000_3.png │ Fig. 5. Bundled ﬂight trails (a). Attribute-based MoleView lens for three altitude levels (b-d)                       │ graph                      │
│ 2156473689 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/2101_6000_0.png │ Fig. 6. Element-based MoleView applied to grayscale angiography image (a-c) and color-mapped trafﬁc speed image (d-f) │ heatmap                    │
│ 2156473689 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/2101_6000_1.png │ Fig. 6. Element-based MoleView applied to grayscale angiography image (a-c) and color-mapped trafﬁc speed image (d-f) │ heatmap                    │
│ 2156473689 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/2101_6000_2.png │ Fig. 6. Element-based MoleView applied to grayscale angiography image (a-c) and color-mapped trafﬁc speed image (d-f) │ heatmap                    │
│ 2156473689 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/2101_6000_3.png │ Fig. 6. Element-based MoleView applied to grayscale angiography image (a-c) and color-mapped trafﬁc speed image (d-f) │ heatmap                    │
│ 2156473689 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/2101_6000_4.png │ Fig. 6. Element-based MoleView applied to grayscale angiography image (a-c) and color-mapped trafﬁc speed image (d-f) │ heatmap                    │
│ 2156473689 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/2101_6000_5.png │ Fig. 6. Element-based MoleView applied to grayscale angiography image (a-c) and color-mapped trafﬁc speed image (d-f) │ heatmap                    │
│ 2156473689 │ https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/2101_7000_0.png │ Fig. 8. Bundle-based exploration (Sec. 2.2). Local unbundling (left). Local bundling (right)                          │ hierarchical_edge_bundling │
├────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────┤
│ ? rows (>9999 rows, 20 shown)                                                                                                                                                                                                                                                      4 columns │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [28]:
len(results)

35024

In [29]:
# now working on making things like citation counts and such visible in the paper data
paper_df = visimages.sql("SELECT * FROM paper").df()

In [30]:
paper_df

,id,title,doi,publication_date,oa_url,pdf_path,inst_id
0,3085563693,Surface representations of two- and three-dime...,https://doi.org/10.1109/visual.1990.146359,2002-12-04,None,None,138006243
1,3041520455,FAST: a multi-processed environment for visual...,https://doi.org/10.1109/visual.1990.146360,2002-12-04,https://jaxa.repo.nii.ac.jp/record/43435/files...,None,138006243
2,4237685258,The VIS-5D system for easy interactive visuali...,https://doi.org/10.1109/visual.1990.146361,2002-12-04,None,None,138006243
3,4241306103,A procedural interface for volume rendering,https://doi.org/10.1109/visual.1990.146362,2002-12-04,None,None,138006243
4,4242274056,Techniques for the interactive visualization o...,https://doi.org/10.1109/visual.1990.146363,2002-12-04,https://escholarship.org/content/qt4367m3t4/qt...,None,138006243
...,...,...,...,...,...,...,...
3048,2889730816,RegressionExplorer: Interactive Exploration of...,https://doi.org/10.1109/tvcg.2018.2865043,2018-09-13,https://pure.tue.nl/ws/files/116894719/0846430...,None,138006243
3049,2963123635,Seq2seq-Vis: A Visual Debugging Tool for Seque...,https://doi.org/10.1109/tvcg.2018.2865044,2018-10-17,https://arxiv.org/pdf/1804.09299,None,138006243
3050,2888244365,"SIRIUS: Dual, Symmetric, Interactive Dimension...",https://doi.org/10.1109/tvcg.2018.2865047,2018-08-20,None,None,138006243
3051,2888207115,MotionRugs: Visualizing Collective Trends in S...,https://doi.org/10.1109/tvcg.2018.2865049,2018-08-20,https://kops.uni-konstanz.de/bitstreams/6238ff...,None,138006243
3052,2886794935,Drag and Track: A Direct Manipulation Interfac...,https://doi.org/10.1109/tvcg.2018.2865051,2018-08-20,None,None,138006243

In [31]:
all_open_alex_data = json.loads(Path("./Hear_me_ROR_out_visimages.json").read_text())

In [32]:
res = []
for e in all_open_alex_data:
    ptopic = e.get("primary_topic",-1)
    if ptopic!=-1 and ptopic != None:
        ptopic = ptopic.get("display_name","")
    else:
        ptopic = ""
    res.append(dict(fwci=e["fwci"],cited_by_count=e["cited_by_count"],referenced_works=e["referenced_works_count"],
         primary_topic=ptopic
    )
              )

res

[{'fwci': 6.892,
  'cited_by_count': 59,
  'referenced_works': 10,
  'primary_topic': 'Fluid Dynamics and Turbulent Flows'},
 {'fwci': 5.675,
  'cited_by_count': 41,
  'referenced_works': 11,
  'primary_topic': 'Fluid Dynamics and Vibration Analysis'},
 {'fwci': 2.605,
  'cited_by_count': 28,
  'referenced_works': 1,
  'primary_topic': 'Distributed and Parallel Computing Systems'},
 {'fwci': 1.148,
  'cited_by_count': 3,
  'referenced_works': 8,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 1.531,
  'cited_by_count': 6,
  'referenced_works': 27,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 0.0,
  'cited_by_count': 0,
  'referenced_works': 32,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 2.192,
  'cited_by_count': 26,
  'referenced_works': 9,
  'primary_topic': 'Advanced Vision and Imaging'},
 {'fwci': 0.0,
  'cited_by_count': 0,
  'referenced_works': 3,
  'primary_topic': 'Image Processing and 3D Reconstruction'},
 {'fwci': 0.822,
  'cited_by_count': 6,
  'referenced_works': 13,
  'primary_topic': 'Medical Image Segmentation Techniques'},
 {'fwci': 0.383,
  'cited_by_count': 3,
  'referenced_works': 6,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 0.274,
  'cited_by_count': 4,
  'referenced_works': 3,
  'primary_topic': 'Data Visualization and Analytics'},
 {'fwci': 0.517,
  'cited_by_count': 2,
  'referenced_works': 4,
  'primary_topic': 'Cinema and Media Studies'},
 {'fwci': 1.397,
  'cited_by_count': 12,
  'referenced_works': 5,
  'primary_topic': 'Cellular Automata and Applications'},
 {'fwci': 0.548,
  'cited_by_count': 13,
  'referenced_works': 16,
  'primary_topic': 'Data Visualization and Analytics'},
 {'fwci': 2.679,
  'cited_by_count': 16,
  'referenced_works': 16,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 0.548,
  'cited_by_count': 14,
  'referenced_works': 23,
  'primary_topic': 'Data Visualization and Analytics'},
 {'fwci': 4.931,
  'cited_by_count': 143,
  'referenced_works': 5,
  'primary_topic': 'Data Visualization and Analytics'},
 {'fwci': 0.822,
  'cited_by_count': 6,
  'referenced_works': 3,
  'primary_topic': 'Digital Image Processing Techniques'},
 {'fwci': 5.74,
  'cited_by_count': 24,
  'referenced_works': 18,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 1.531,
  'cited_by_count': 16,
  'referenced_works': 21,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 0.303,
  'cited_by_count': 10,
  'referenced_works': 15,
  'primary_topic': 'Data Management and Algorithms'},
 {'fwci': 0.0,
  'cited_by_count': 7,
  'referenced_works': 8,
  'primary_topic': '3D Modeling in Geospatial Applications'},
 {'fwci': 0.811,
  'cited_by_count': 6,
  'referenced_works': 5,
  'primary_topic': 'Advanced Numerical Analysis Techniques'},
 {'fwci': 0.765,
  'cited_by_count': 4,
  'referenced_works': 8,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 0.201,
  'cited_by_count': 14,
  'referenced_works': 12,
  'primary_topic': 'Color Science and Applications'},
 {'fwci': 0.0,
  'cited_by_count': 7,
  'referenced_works': 6,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 0.0,
  'cited_by_count': 1,
  'referenced_works': 9,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 9.589,
  'cited_by_count': 112,
  'referenced_works': 12,
  'primary_topic': 'Data Visualization and Analytics'},
 {'fwci': 4.383,
  'cited_by_count': 53,
  'referenced_works': 2,
  'primary_topic': 'Image Retrieval and Classification Techniques'},
 {'fwci': 1.148,
  'cited_by_count': 9,
  'referenced_works': 25,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 1.918,
  'cited_by_count': 15,
  'referenced_works': 1,
  'primary_topic': 'Data Visualization and Analytics'},
 {'fwci': 0.766,
  'cited_by_count': 4,
  'referenced_works': 17,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 0.766,
  'cited_by_count': 10,
  'referenced_works': 21,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 0.0,
  'cited_by_count': 1,
  'referenced_works': 5,
  'primary_topic': 'Distributed and Parallel Computing Systems'},
 {'fwci': 0.0,
  'cited_by_count': 0,
  'referenced_works': 19,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 0.0,
  'cited_by_count': 1,
  'referenced_works': 12,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 5.031,
  'cited_by_count': 14,
  'referenced_works': 10,
  'primary_topic': '3D Modeling in Geospatial Applications'},
 {'fwci': 0.0,
  'cited_by_count': 0,
  'referenced_works': 12,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 0.765,
  'cited_by_count': 5,
  'referenced_works': 6,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 0.57,
  'cited_by_count': 22,
  'referenced_works': 30,
  'primary_topic': 'Tactile and Sensory Interactions'},
 {'fwci': 0.0,
  'cited_by_count': 0,
  'referenced_works': 5,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 0.0,
  'cited_by_count': 0,
  'referenced_works': 23,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 0.383,
  'cited_by_count': 5,
  'referenced_works': 14,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 21.096,
  'cited_by_count': 485,
  'referenced_works': 21,
  'primary_topic': 'Data Visualization and Analytics'},
 {'fwci': 0.0,
  'cited_by_count': 0,
  'referenced_works': 19,
  'primary_topic': 'Architecture and Computational Design'},
 {'fwci': 0.0,
  'cited_by_count': 1,
  'referenced_works': 1,
  'primary_topic': 'Color Science and Applications'},
 {'fwci': 0.21,
  'cited_by_count': 3,
  'referenced_works': 10,
  'primary_topic': 'Advanced Fluorescence Microscopy Techniques'},
 {'fwci': 0.0,
  'cited_by_count': 0,
  'referenced_works': 0,
  'primary_topic': 'Online Learning and Analytics'},
 {'fwci': 0.167,
  'cited_by_count': 1,
  'referenced_works': 7,
  'primary_topic': 'Spaceflight effects on biology'},
 {'fwci': 0.0,
  'cited_by_count': 9,
  'referenced_works': 3,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 0.0,
  'cited_by_count': 0,
  'referenced_works': 0,
  'primary_topic': 'Data Visualization and Analytics'},
 {'fwci': 0.0,
  'cited_by_count': 0,
  'referenced_works': 2,
  'primary_topic': 'Distributed and Parallel Computing Systems'},
 {'fwci': 0.548,
  'cited_by_count': 2,
  'referenced_works': 3,
  'primary_topic': 'Robotic Path Planning Algorithms'},
 {'fwci': 0.0,
  'cited_by_count': 0,
  'referenced_works': 0,
  'primary_topic': 'Distributed and Parallel Computing Systems'},
 {'fwci': 0.822,
  'cited_by_count': 6,
  'referenced_works': 6,
  'primary_topic': 'Data Visualization and Analytics'},
 {'fwci': 9.727,
  'cited_by_count': 57,
  'referenced_works': 9,
  'primary_topic': 'Fluid Dynamics and Turbulent Flows'},
 {'fwci': 1.148,
  'cited_by_count': 4,
  'referenced_works': 21,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 19.048,
  'cited_by_count': 132,
  'referenced_works': 27,
  'primary_topic': 'Fluid Dynamics and Turbulent Flows'},
 {'fwci': 0.0,
  'cited_by_count': 0,
  'referenced_works': 8,
  'primary_topic': 'Advanced Vision and Imaging'},
 {'fwci': 5.359,
  'cited_by_count': 21,
  'referenced_works': 20,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 2.296,
  'cited_by_count': 14,
  'referenced_works': 13,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 5.741,
  'cited_by_count': 23,
  'referenced_works': 18,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 0.0,
  'cited_by_count': 1,
  'referenced_works': 22,
  'primary_topic': 'Experimental Learning in Engineering'},
 {'fwci': 24.729,
  'cited_by_count': 214,
  'referenced_works': 11,
  'primary_topic': 'Advanced Numerical Analysis Techniques'},
 {'fwci': 0.852,
  'cited_by_count': 6,
  'referenced_works': 9,
  'primary_topic': 'Underwater Acoustics Research'},
 {'fwci': 0.0,
  'cited_by_count': 0,
  'referenced_works': 2,
  'primary_topic': 'Advanced Theoretical and Applied Studies in Material Sciences and Geometry'},
 {'fwci': 0.0,
  'cited_by_count': 2,
  'referenced_works': 7,
  'primary_topic': 'Silicon and Solar Cell Technologies'},
 {'fwci': 0.305,
  'cited_by_count': 1,
  'referenced_works': 9,
  'primary_topic': 'Sports Dynamics and Biomechanics'},
 {'fwci': 8.802,
  'cited_by_count': 43,
  'referenced_works': 7,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 0.822,
  'cited_by_count': 24,
  'referenced_works': 8,
  'primary_topic': 'Data Visualization and Analytics'},
 {'fwci': 0.274,
  'cited_by_count': 1,
  'referenced_works': 6,
  'primary_topic': 'Data Visualization and Analytics'},
 {'fwci': 1.006,
  'cited_by_count': 13,
  'referenced_works': 6,
  'primary_topic': '3D Modeling in Geospatial Applications'},
 {'fwci': 6.575,
  'cited_by_count': 134,
  'referenced_works': 19,
  'primary_topic': 'Data Visualization and Analytics'},
 {'fwci': 3.096,
  'cited_by_count': 31,
  'referenced_works': 10,
  'primary_topic': 'Color perception and design'},
 {'fwci': 2.573,
  'cited_by_count': 11,
  'referenced_works': 5,
  'primary_topic': ''},
 {'fwci': 0.858,
  'cited_by_count': 3,
  'referenced_works': 8,
  'primary_topic': ''},
 {'fwci': 0.0,
  'cited_by_count': 1,
  'referenced_works': 7,
  'primary_topic': 'Geological Modeling and Analysis'},
 {'fwci': 0.0,
  'cited_by_count': 7,
  'referenced_works': 17,
  'primary_topic': 'Neural dynamics and brain function'},
 {'fwci': 0.265,
  'cited_by_count': 9,
  'referenced_works': 6,
  'primary_topic': 'Advanced MRI Techniques and Applications'},
 {'fwci': 0.414,
  'cited_by_count': 1,
  'referenced_works': 9,
  'primary_topic': 'AI in cancer detection'},
 {'fwci': 0.765,
  'cited_by_count': 4,
  'referenced_works': 20,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 0.765,
  'cited_by_count': 14,
  'referenced_works': 19,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 0.376,
  'cited_by_count': 7,
  'referenced_works': 15,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 1.913,
  'cited_by_count': 9,
  'referenced_works': 10,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 1.37,
  'cited_by_count': 9,
  'referenced_works': 2,
  'primary_topic': 'Data Visualization and Analytics'},
 {'fwci': 0.868,
  'cited_by_count': 9,
  'referenced_works': 7,
  'primary_topic': 'Distributed and Parallel Computing Systems'},
 {'fwci': 1.148,
  'cited_by_count': 11,
  'referenced_works': 7,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 1.866,
  'cited_by_count': 6,
  'referenced_works': 4,
  'primary_topic': 'Advanced Data Processing Techniques'},
 {'fwci': 1.096,
  'cited_by_count': 6,
  'referenced_works': 1,
  'primary_topic': 'Medical Image Segmentation Techniques'},
 {'fwci': 23.287,
  'cited_by_count': 520,
  'referenced_works': 17,
  'primary_topic': 'Data Visualization and Analytics'},
 {'fwci': 0.0,
  'cited_by_count': 0,
  'referenced_works': 2,
  'primary_topic': 'Advanced Data Storage Technologies'},
 {'fwci': 4.383,
  'cited_by_count': 32,
  'referenced_works': 5,
  'primary_topic': 'Data Visualization and Analytics'},
 {'fwci': 0.822,
  'cited_by_count': 7,
  'referenced_works': 11,
  'primary_topic': 'Data Visualization and Analytics'},
 {'fwci': 0.274,
  'cited_by_count': 11,
  'referenced_works': 1,
  'primary_topic': 'Data Visualization and Analytics'},
 {'fwci': 2.296,
  'cited_by_count': 15,
  'referenced_works': 10,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 0.383,
  'cited_by_count': 3,
  'referenced_works': 9,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 0.274,
  'cited_by_count': 2,
  'referenced_works': 0,
  'primary_topic': 'Data Visualization and Analytics'},
 {'fwci': 0.0,
  'cited_by_count': 2,
  'referenced_works': 0,
  'primary_topic': 'Multimedia Communication and Technology'},
 {'fwci': 0.0,
  'cited_by_count': 0,
  'referenced_works': 0,
  'primary_topic': 'Manufacturing Process and Optimization'},
 {'fwci': 0.822,
  'cited_by_count': 4,
  'referenced_works': 12,
  'primary_topic': 'Data Visualization and Analytics'},
 {'fwci': 0.0,
  'cited_by_count': 0,
  'referenced_works': 4,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 0.289,
  'cited_by_count': 1,
  'referenced_works': 0,
  'primary_topic': 'Distributed and Parallel Computing Systems'},
 {'fwci': 0.0,
  'cited_by_count': 0,
  'referenced_works': 1,
  'primary_topic': 'History and advancements in chemistry'},
 {'fwci': 0.0,
  'cited_by_count': 0,
  'referenced_works': 0,
  'primary_topic': 'Simulation and Modeling Applications'},
 {'fwci': 1.531,
  'cited_by_count': 8,
  'referenced_works': 2,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 0.289,
  'cited_by_count': 4,
  'referenced_works': 3,
  'primary_topic': 'Distributed and Parallel Computing Systems'},
 {'fwci': 0.0,
  'cited_by_count': 0,
  'referenced_works': 0,
  'primary_topic': 'Distributed and Parallel Computing Systems'},
 {'fwci': 0.596,
  'cited_by_count': 1,
  'referenced_works': 4,
  'primary_topic': 'Interdisciplinary Research and Collaboration'},
 {'fwci': 2.297,
  'cited_by_count': 13,
  'referenced_works': 8,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 0.0,
  'cited_by_count': 1,
  'referenced_works': 1,
  'primary_topic': 'Scientific Computing and Data Management'},
 {'fwci': 0.0,
  'cited_by_count': 0,
  'referenced_works': 0,
  'primary_topic': 'Reservoir Engineering and Simulation Methods'},
 {'fwci': None,
  'cited_by_count': 3,
  'referenced_works': 10,
  'primary_topic': ''},
 {'fwci': 0.0,
  'cited_by_count': 0,
  'referenced_works': 5,
  'primary_topic': 'Meteorological Phenomena and Simulations'},
 {'fwci': 0.0,
  'cited_by_count': 0,
  'referenced_works': 10,
  'primary_topic': 'Geophysics and Gravity Measurements'},
 {'fwci': 0.0,
  'cited_by_count': 0,
  'referenced_works': 12,
  'primary_topic': 'Data Visualization and Analytics'},
 {'fwci': 0.836,
  'cited_by_count': 11,
  'referenced_works': 9,
  'primary_topic': 'Computational Physics and Python Applications'},
 {'fwci': 0.0,
  'cited_by_count': 4,
  'referenced_works': 13,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 0.0,
  'cited_by_count': 0,
  'referenced_works': 4,
  'primary_topic': 'Computational Physics and Python Applications'},
 {'fwci': 0.171,
  'cited_by_count': 1,
  'referenced_works': 7,
  'primary_topic': 'History and Developments in Astronomy'},
 {'fwci': 1.437,
  'cited_by_count': 8,
  'referenced_works': 0,
  'primary_topic': 'Distributed and Parallel Computing Systems'},
 {'fwci': 0.0,
  'cited_by_count': 0,
  'referenced_works': 0,
  'primary_topic': 'Cell Image Analysis Techniques'},
 {'fwci': 0.782,
  'cited_by_count': 2,
  'referenced_works': 0,
  'primary_topic': 'Simulation and Modeling Applications'},
 {'fwci': 0.0,
  'cited_by_count': 2,
  'referenced_works': 0,
  'primary_topic': 'Educational Games and Gamification'},
 {'fwci': 0.0,
  'cited_by_count': 6,
  'referenced_works': 9,
  'primary_topic': 'Data Visualization and Analytics'},
 {'fwci': 0.479,
  'cited_by_count': 5,
  'referenced_works': 0,
  'primary_topic': 'Distributed and Parallel Computing Systems'},
 {'fwci': 0.0,
  'cited_by_count': 2,
  'referenced_works': 3,
  'primary_topic': 'Land Use and Ecosystem Services'},
 {'fwci': 0.447,
  'cited_by_count': 11,
  'referenced_works': 22,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 0.895,
  'cited_by_count': 13,
  'referenced_works': 8,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 1.789,
  'cited_by_count': 12,
  'referenced_works': 12,
  'primary_topic': 'Computational Geometry and Mesh Generation'},
 {'fwci': 0.0,
  'cited_by_count': 1,
  'referenced_works': 5,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 3.345,
  'cited_by_count': 31,
  'referenced_works': 14,
  'primary_topic': 'Computational Physics and Python Applications'},
 {'fwci': 0.0,
  'cited_by_count': 3,
  'referenced_works': 12,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 0.0,
  'cited_by_count': 0,
  'referenced_works': 1,
  'primary_topic': 'Peer-to-Peer Network Technologies'},
 {'fwci': 0.398,
  'cited_by_count': 7,
  'referenced_works': 9,
  'primary_topic': 'Astronomical Observations and Instrumentation'},
 {'fwci': 0.287,
  'cited_by_count': 8,
  'referenced_works': 9,
  'primary_topic': 'Data Visualization and Analytics'},
 {'fwci': 0.86,
  'cited_by_count': 19,
  'referenced_works': 13,
  'primary_topic': 'Image Retrieval and Classification Techniques'},
 {'fwci': 0.836,
  'cited_by_count': 21,
  'referenced_works': 4,
  'primary_topic': 'Neural Networks and Applications'},
 {'fwci': 0.195,
  'cited_by_count': 3,
  'referenced_works': 9,
  'primary_topic': 'Color Science and Applications'},
 {'fwci': 0.358,
  'cited_by_count': 12,
  'referenced_works': 11,
  'primary_topic': 'Color perception and design'},
 {'fwci': 0.462,
  'cited_by_count': 11,
  'referenced_works': 11,
  'primary_topic': 'Scientific Computing and Data Management'},
 {'fwci': 2.007,
  'cited_by_count': 46,
  'referenced_works': 9,
  'primary_topic': 'Data Visualization and Analytics'},
 {'fwci': 1.342,
  'cited_by_count': 15,
  'referenced_works': 9,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 0.0,
  'cited_by_count': 11,
  'referenced_works': 12,
  'primary_topic': 'Distributed and Parallel Computing Systems'},
 {'fwci': 0.0,
  'cited_by_count': 54,
  'referenced_works': 7,
  'primary_topic': 'Software Testing and Debugging Techniques'},
 {'fwci': 0.0,
  'cited_by_count': 14,
  'referenced_works': 7,
  'primary_topic': 'Scientific Computing and Data Management'},
 {'fwci': 0.0,
  'cited_by_count': 2,
  'referenced_works': 12,
  'primary_topic': 'Advanced Database Systems and Queries'},
 {'fwci': 0.292,
  'cited_by_count': 4,
  'referenced_works': 14,
  'primary_topic': 'Parallel Computing and Optimization Techniques'},
 {'fwci': 0.237,
  'cited_by_count': 32,
  'referenced_works': 10,
  'primary_topic': 'Meteorological Phenomena and Simulations'},
 {'fwci': 8.946,
  'cited_by_count': 108,
  'referenced_works': 10,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 0.0,
  'cited_by_count': 4,
  'referenced_works': 13,
  'primary_topic': 'Aerodynamics and Acoustics in Jet Flows'},
 {'fwci': 0.0,
  'cited_by_count': 7,
  'referenced_works': 6,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 0.0,
  'cited_by_count': 2,
  'referenced_works': 12,
  'primary_topic': 'Image and Object Detection Techniques'},
 {'fwci': 1.342,
  'cited_by_count': 14,
  'referenced_works': 6,
  'primary_topic': 'Computer Graphics and Visualization Techniques'},
 {'fwci': 0.0,
  'cited_by_count': 1,
  'referenced_works': 4,
  'primary_topic': 'Satellite Image Processing and Photogrammetry'},
 {'fwci': 2.581,
  'cited_by_count': 31,
  'referenced_works': 13,
  'primary_topic': 'Data Visualization and Analytics'},
 {'fwci': 0.0,
  'cited_by_count': 2,
  'referenced_works': 22,
  'primary_topic': 'Geological Modeling and Analysis'},
 {'fwci': 2.359,
  'cited_by_count': 61,
  'referenced_works': 6,
  'primary_topic': 'Distributed and Parallel Computing Systems'},

In [33]:
paper_citation_df = pd.DataFrame(res)

In [34]:
all_paper_df = pd.concat([paper_df,paper_citation_df],axis=1)

In [35]:
visimages.sql("DROP TABLE paper")

In [36]:
visimages.sql("CREATE TABLE paper AS SELECT * FROM all_paper_df")

In [37]:
visimages.execute("EXPORT DATABASE 'visimages_parquet' (FORMAT parquet)")

In [38]:
results[8000]

{'paper_id': 2170910862,
 'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1968_8000_1.png',
 'caption': 'Fig. 10. Visualization of the Pollen data set: (a) Scatterplot; (b) Con- ventional parallel coordinates; (c) Brightness used to represent density of proﬁles; (d) Interactive Parallel Coordinates Frequency Plots with a brightness gradient; (e) Parallel coordinate plot with line stacks; (f) The central stacks colored by height; (g) Scatterplot of the subset of points in (f).',
 'chart_type': 'parallel_coordinate'}

In [39]:
visimages.sql("SELECT * FROM paper WHERE id = 2170910862").show()

┌────────────┬──────────────────────────────────────────────────┬───────────────────────────────────────┬─────────────────────┬─────────┬──────────┬───────────┬────────┬────────────────┬──────────────────┬──────────────────────────────────┐
│     id     │                      title                       │                  doi                  │  publication_date   │ oa_url  │ pdf_path │  inst_id  │  fwci  │ cited_by_count │ referenced_works │          primary_topic           │
│   int64    │                     varchar                      │                varchar                │      timestamp      │ varchar │  int32   │   int64   │ double │     int64      │      int64       │             varchar              │
├────────────┼──────────────────────────────────────────────────┼───────────────────────────────────────┼─────────────────────┼─────────┼──────────┼───────────┼────────┼────────────────┼──────────────────┼──────────────────────────────────┤
│ 2170910862 │ Stacking Graphic Elements to Avoid Over-Plotting │ https://doi.org/10.1109/tvcg.2010.197 │ 2010-11-01 00:00:00 │ None    │     NULL │ 138006243 │  3.153 │             69 │               48 │ Data Visualization and Analytics │
└────────────┴──────────────────────────────────────────────────┴───────────────────────────────────────┴─────────────────────┴─────────┴──────────┴───────────┴────────┴────────────────┴──────────────────┴──────────────────────────────────┘

In [40]:
results[0]

{'paper_id': 2165915693,
 'server_path': 'https://data.cyverse.org/dav-anon/iplant/home/carolinarr/vis-sieve/zhiyang_visimages_subfigures/subfigures/1021_0000_0.png',
 'caption': 'Figure 2: u, w space diagram',
 'chart_type': 'line_chart'}

In [41]:
metadata.iloc[1028]

journal                                              InfoVis
title       Multiscale Visualization of Small World Networks
doi                              10.1109/INFVIS.2003.1249011
link       http://doi.ieeecomputersociety.org/10.1109/INF...
Name: 1028, dtype: object

In [42]:
annotation_paper_id

'938'

In [43]:
dois[dois.metadata_index == 3060]

,journal,title,doi,link,metadata_index,database_index
3060,VAST,iForest: Interpreting Random Forests via Visua...,10.1109/TVCG.2018.2864475,http://dx.doi.org/10.1109/TVCG.2018.2864475,3060,3012

In [46]:
visimages.close()